export const ADD_PRENOTAZIONI = 'ADD_PRENOTAZIONI';
export const ADD_PRENOTAZIONE = 'ADD_PRENOTAZIONE';
export const LOADING_PRENOTAZIONI = 'LOADING_PRENOTAZIONI';
export const FAILED_PRENOTAZIONI = 'FAILED_PRENOTAZIONI';

export const ADD_PRENOTAZIONI_ADMIN = 'ADD_PRENOTAZIONI_ADMIN';
export const ADD_PRENOTAZIONE_ADMIN = 'ADD_PRENOTAZIONE_ADMIN';
export const DEL_PRENOTAZIONE_ADMIN = 'DEL_PRENOTAZIONE_ADMIN';
export const UPDATE_PRENOTAZIONE_ADMIN = 'UPDATE_PRENOTAZIONE_ADMIN';
export const LOADING_PRENOTAZIONI_ADMIN = 'LOADING_PRENOTAZIONI_ADMIN';
export const FAILED_PRENOTAZIONI_ADMIN = 'FAILED_PRENOTAZIONI_ADMIN';

export const ADD_ATTIVITA = 'ADD_ATTIVITA';
export const LOADING_ATTIVITA = 'LOADING_ATTIVITA';
export const FAILED_ATTIVITA = 'FAILED_ATTIVITA';

export const ADD_UTENTE = 'ADD_UTENTE';
export const LOADING_UTENTE = 'LOADING_UTENTE';
export const FAILED_UTENTE = 'FAILED_UTENTE';

