export const ADD_PRENOTAZIONI = 'ADD_PRENOTAZIONI';
export const ADD_PRENOTAZIONE = 'ADD_PRENOTAZIONE';
export const DEL_PRENOTAZIONE = 'DEL_PRENOTAZIONE';
export const UPDATE_PRENOTAZIONE = 'UPDATE_PRENOTAZIONE';
export const LOADING_PRENOTAZIONI = 'LOADING_PRENOTAZIONI';
export const FAILED_PRENOTAZIONI = 'FAILED_PRENOTAZIONI';